# sim/configs/backtest_001.yaml

model_id: xgb_momentum_001
tickers_file: data/dev/tickers-dev.txt

strategy: hold_n_hours
strategy_params:
  top_k: 5
  hold_hours: 3

initial_budget: 1000
cooldown_hours: 3

# New date-range fields for the backtest
start_date: "2025-06-04"
end_date:   "2025-06-20"
